version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    container_name: dockerNodeGraphql_postgres

  web:
    build: .
    command: bash -c "yarn install && yarn run start:server"
    volumes:
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - '8080:8080'
      - '3000:3000'
    depends_on:
      - db
    environment:
      DATABASE: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      #database container name.
      DATABASE_CONTAINER: dockerNodeGraphql_postgres
      # change the secret  when you pull this and put into prod.
      SECRET: A.1238789783432098.7p[[p[wkfsd/fmd.fj
      #port the graphql server is on
      SERVER_PORT: 3000,
      #CLIENT PORT
      CLIENT_PORT: 8080,
